package com.example.pullit.ui

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // ── Common ──
    val cancel: String,
    val delete: String,
    val create: String,
    val save: String,
    val back: String,
    val add: String,
    val done: String,
    val processing: String,
    val tryAgain: String,

    // ── Greeting ──
    val goodMorning: String,
    val goodAfternoon: String,
    val goodEvening: String,

    // ── Tabs / Navigation ──
    val allRecipes: String,
    val cookbooks: String,
    val mealPlan: String,
    val more: String,

    // ── Recipe List ──
    val searchRecipes: String,
    val newestFirst: String,
    val oldestFirst: String,
    val byName: String,
    val selected: String,
    val addToCookbook: String,
    val noSavedRecipes: String,
    val noSavedRecipesHint: String,
    val noRecipesFound: String,
    val noRecipesFoundHint: String,
    val noRecipes: String,
    val noRecipesHint: String,
    val generatingRecipe: String,
    val tapToViewRecipe: String,
    val noCookbooks: String,
    val noCookbooksHint: String,
    val createCookbook: String,
    val newCookbook: String,
    val cookbookName: String,

    // ── Recipe Detail ──
    val deleteRecipe: String,
    val cannotUndo: String,
    val ingredients: String,
    val steps: String,
    val servings: String,
    val addToCookbookBtn: String,
    val addToMealPlan: String,
    val added: String,
    val startCooking: String,
    val shareRecipe: String,
    val shareAsText: String,
    val shareAsTextHint: String,
    val shareAsImage: String,
    val shareAsImageHint: String,
    val openSourceUrl: String,

    // ── More Screen ──
    val pullitRecipes: String,
    val personalAssistant: String,
    val recipes: String,
    val favorites: String,
    val general: String,
    val language: String,
    val followSystem: String,
    val appearance: String,
    val lightMode: String,
    val darkMode: String,
    val autoDetectClipboard: String,
    val content: String,
    val importExport: String,
    val support: String,
    val privacyInfo: String,
    val privacyPolicy: String,
    val feedbackGroup: String,
    val rateUs: String,
    val aboutPullit: String,
    val account: String,
    val email: String,
    val displayName: String,
    val signOut: String,
    val signOutConfirm: String,
    val signOutMessage: String,
    val version: String,

    // ── Import Sheet ──
    val importRecipe: String,
    val supportedPlatforms: String,
    val xiaohongshu: String,
    val douyin: String,
    val xiachufang: String,
    val pasteLink: String,
    val paste: String,
    val orImportFrom: String,
    val photo: String,
    val text: String,
    val link: String,
    val image: String,
    val pasteRecipeText: String,
    val changeImage: String,
    val chooseImage: String,
    val selectedImage: String,

    // ── Meal Plan ──
    val weeklyPlan: String,
    val groceryList: String,
    val startPlanning: String,
    val startPlanningHint: String,
    val addRecipes: String,
    val generateGroceryList: String,
    val clearAll: String,
    val inPlan: String,
    val serving: String,
    val servingsUnit: String,

    // ── AI Recommend ──
    val aiRecommend: String,
    val aiIngredientRecognition: String,
    val aiIngredientHint: String,
    val choosePhoto: String,
    val aiAnalyzing: String,
    val foundIngredients: String,
    val addIngredient: String,
    val getAiSuggestions: String,
    val newPhoto: String,
    val yourMatchingRecipes: String,
    val aiSuggestions: String,
    val generatingSuggestions: String,
    val somethingWentWrong: String,

    // ── Recipe Edit ──
    val editRecipe: String,
    val coverImage: String,
    val addCoverPhoto: String,
    val basicInfo: String,
    val title: String,
    val description: String,
    val cookTime: String,
    val nutrition: String,
    val collapse: String,
    val expand: String,
    val calories: String,
    val protein: String,
    val fat: String,
    val carbs: String,
    val name: String,
    val amount: String,
    val section: String,
    val sectionOptional: String,
    val addIngredient2: String,
    val addStep: String,

    // ── Roulette ──
    val recipeRoulette: String,
    val noRecipesToSpin: String,
    val addSomeRecipes: String,
    val viewRecipe: String,
    val spinAgain: String,
    val tapToSpin: String,
    val spinToPick: String,

    // ── Cooking Mode ──
    val setTimer: String,
    val minutes: String,
    val seconds: String,
    val start: String,
    val pause: String,
    val play: String,
    val reset: String,

    // ── Auth ──
    val yourRecipeCompanion: String,
    val emailPlaceholder: String,
    val password: String,
    val signUp: String,
    val signIn: String,
    val alreadyHaveAccount: String,
    val dontHaveAccount: String,

    // ── Display Name Setup ──
    val whatShouldWeCallYou: String,
    val pickDisplayName: String,
    val displayNamePlaceholder: String,
    val atLeast2Chars: String,
    val continueBtn: String,

    // ── Grocery List ──
    val addAnItem: String,
    val noItemsYet: String,
    val noItemsHint: String,
    val toBuy: String,
    val bought: String,
    val clearBought: String,
    val fromMealPlan: String,

    // ── Suggestion Detail ──
    val recipeDetail: String,
    val savedToRecipes: String,
    val saveToRecipes: String,
    val kcal: String,
    val step: String,

    // ── Privacy Info ──
    val privacyTitle: String,
    val privacySubtitle: String,
    val privacyLocalStorageTitle: String,
    val privacyLocalStorageDetail: String,
    val privacyDataSentTitle: String,
    val privacyDataSentDetail: String,
    val privacyThirdPartyTitle: String,
    val privacyThirdPartyDetail: String,
    val privacyDataDeletionTitle: String,
    val privacyDataDeletionDetail: String,
    val privacyEncryptionTitle: String,
    val privacyEncryptionDetail: String,
    val privacyPolicyLink: String,
    val privacyAgreeButton: String,
)

val EnglishStrings = AppStrings(
    cancel = "Cancel",
    delete = "Delete",
    create = "Create",
    save = "Save",
    back = "Back",
    add = "Add",
    done = "Done",
    processing = "Processing...",
    tryAgain = "Try Again",
    goodMorning = "Good morning",
    goodAfternoon = "Good afternoon",
    goodEvening = "Good evening",
    allRecipes = "All Recipes",
    cookbooks = "Cookbooks",
    mealPlan = "Meal Plan",
    more = "More",
    searchRecipes = "Search recipes...",
    newestFirst = "Newest first",
    oldestFirst = "Oldest first",
    byName = "By name",
    selected = "selected",
    addToCookbook = "Add to Cookbook",
    noSavedRecipes = "No saved recipes",
    noSavedRecipesHint = "Tap the heart to save recipes you like",
    noRecipesFound = "No recipes found",
    noRecipesFoundHint = "Try other keywords",
    noRecipes = "No recipes yet",
    noRecipesHint = "Tap + to import your first recipe",
    generatingRecipe = "Generating recipe...",
    tapToViewRecipe = "Tap to view recipe",
    noCookbooks = "No cookbooks yet",
    noCookbooksHint = "Create cookbooks to organize your recipes",
    createCookbook = "Create Cookbook",
    newCookbook = "New Cookbook",
    cookbookName = "Cookbook name",
    deleteRecipe = "Delete recipe?",
    cannotUndo = "This cannot be undone.",
    ingredients = "Ingredients",
    steps = "Steps",
    servings = "Servings",
    addToCookbookBtn = "Add to Cookbook",
    addToMealPlan = "Add to Meal Plan",
    added = "Added",
    startCooking = "Start Cooking",
    shareRecipe = "Share Recipe",
    shareAsText = "Share as Text",
    shareAsTextHint = "Copy recipe text content",
    shareAsImage = "Share as Image",
    shareAsImageHint = "Generate recipe card image",
    openSourceUrl = "Open Source URL",
    pullitRecipes = "Pullit Recipes",
    personalAssistant = "Your personal recipe assistant",
    recipes = "Recipes",
    favorites = "Favorites",
    general = "General",
    language = "Language",
    followSystem = "Follow System",
    appearance = "Appearance",
    lightMode = "Light Mode",
    darkMode = "Dark Mode",
    autoDetectClipboard = "Auto-detect Clipboard",
    content = "Content",
    importExport = "Import / Export",
    support = "Support",
    privacyInfo = "Privacy Info",
    privacyPolicy = "Privacy Policy",
    feedbackGroup = "Feedback Group",
    rateUs = "Rate Us",
    aboutPullit = "About Pullit",
    account = "Account",
    email = "Email",
    displayName = "Display Name",
    signOut = "Sign Out",
    signOutConfirm = "Sign Out?",
    signOutMessage = "You can sign back in anytime.",
    version = "Pullit Recipes v1.0",
    importRecipe = "Import Recipe",
    supportedPlatforms = "Supported Platforms",
    xiaohongshu = "Xiaohongshu",
    douyin = "Douyin",
    xiachufang = "Xiachufang",
    pasteLink = "Paste link or share text here...",
    paste = "Paste",
    orImportFrom = "Or Import From",
    photo = "Photo",
    text = "Text",
    link = "Link",
    image = "Image",
    pasteRecipeText = "Paste recipe text here...",
    changeImage = "Change Image",
    chooseImage = "Choose Image",
    selectedImage = "Selected image",
    weeklyPlan = "Weekly Plan",
    groceryList = "Grocery List",
    startPlanning = "Start Planning",
    startPlanningHint = "Add recipes to plan your meals for the week",
    addRecipes = "Add Recipes",
    generateGroceryList = "Generate Grocery List",
    clearAll = "Clear All",
    inPlan = "In plan",
    serving = "serving",
    servingsUnit = "servings",
    aiRecommend = "AI Recommend",
    aiIngredientRecognition = "AI Ingredient Recognition",
    aiIngredientHint = "Take a photo of your ingredients and we'll suggest recipes you can make",
    choosePhoto = "Choose Photo",
    aiAnalyzing = "AI Analyzing...",
    foundIngredients = "Found Ingredients",
    addIngredient = "Add ingredient...",
    getAiSuggestions = "Get AI Suggestions",
    newPhoto = "New Photo",
    yourMatchingRecipes = "Your Matching Recipes",
    aiSuggestions = "AI Suggestions",
    generatingSuggestions = "Generating suggestions...",
    somethingWentWrong = "Something went wrong",
    editRecipe = "Edit Recipe",
    coverImage = "Cover Image",
    addCoverPhoto = "Add Cover Photo",
    basicInfo = "Basic Info",
    title = "Title",
    description = "Description",
    cookTime = "Cook Time",
    nutrition = "Nutrition",
    collapse = "Collapse",
    expand = "Expand",
    calories = "Calories",
    protein = "Protein",
    fat = "Fat",
    carbs = "Carbs",
    name = "Name",
    amount = "Amount",
    section = "+ Section",
    sectionOptional = "Section (optional)",
    addIngredient2 = "Add Ingredient",
    addStep = "Add Step",
    recipeRoulette = "Recipe Roulette",
    noRecipesToSpin = "No recipes to spin",
    addSomeRecipes = "Add some recipes first!",
    viewRecipe = "View Recipe",
    spinAgain = "Spin Again",
    tapToSpin = "Tap to Spin",
    spinToPick = "Spin to pick!",
    setTimer = "Set Timer",
    minutes = "Minutes",
    seconds = "Seconds",
    start = "Start",
    pause = "Pause",
    play = "Play",
    reset = "Reset",
    yourRecipeCompanion = "Your recipe companion",
    emailPlaceholder = "you@example.com",
    password = "Password",
    signUp = "Sign Up",
    signIn = "Sign In",
    alreadyHaveAccount = "Already have an account? Sign In",
    dontHaveAccount = "Don't have an account? Sign Up",
    whatShouldWeCallYou = "What should we call you?",
    pickDisplayName = "Pick a display name for your profile.\nYou can change it later.",
    displayNamePlaceholder = "Display name",
    atLeast2Chars = "At least 2 characters",
    continueBtn = "Continue",
    addAnItem = "Add an item...",
    noItemsYet = "No items yet",
    noItemsHint = "Add items or generate from your meal plan",
    toBuy = "To Buy",
    bought = "Bought",
    clearBought = "Clear Bought",
    fromMealPlan = "From meal plan",
    recipeDetail = "Recipe Detail",
    savedToRecipes = "Saved to Recipes",
    saveToRecipes = "Save to Recipes",
    kcal = "kcal",
    step = "Step",
    privacyTitle = "Data & Privacy",
    privacySubtitle = "Here's how Pullit handles your data when you use AI-powered features",
    privacyLocalStorageTitle = "Local Storage",
    privacyLocalStorageDetail = "Your recipes, cookbooks, and meal plans are stored only on your device and never uploaded to our servers.",
    privacyDataSentTitle = "Data Sent for AI Features",
    privacyDataSentDetail = "When you import via link, recognize ingredients by photo, or use AI recommendations, the relevant data (links or images) is sent to our server for processing.",
    privacyThirdPartyTitle = "Third-Party AI Services",
    privacyThirdPartyDetail = "Our server uses Groq (groq.com) and OpenRouter (openrouter.ai) to process your data for recipe generation and ingredient recognition.",
    privacyDataDeletionTitle = "Immediate Deletion",
    privacyDataDeletionDetail = "Images and video data are deleted immediately after processing. Only the structured recipe result is returned to your device.",
    privacyEncryptionTitle = "Encrypted Transmission",
    privacyEncryptionDetail = "All data is transmitted via HTTPS encryption between your device and our servers.",
    privacyPolicyLink = "View Full Privacy Policy",
    privacyAgreeButton = "Agree & Continue",
)

val ChineseStrings = AppStrings(
    cancel = "取消",
    delete = "删除",
    create = "创建",
    save = "保存",
    back = "返回",
    add = "添加",
    done = "完成",
    processing = "处理中...",
    tryAgain = "重试",
    goodMorning = "早上好",
    goodAfternoon = "下午好",
    goodEvening = "晚上好",
    allRecipes = "所有食谱",
    cookbooks = "食谱集",
    mealPlan = "膳食计划",
    more = "更多",
    searchRecipes = "搜索食谱...",
    newestFirst = "最新优先",
    oldestFirst = "最旧优先",
    byName = "按名称",
    selected = "已选择",
    addToCookbook = "加入食谱集",
    noSavedRecipes = "还没有收藏的食谱",
    noSavedRecipesHint = "点击爱心收藏你喜欢的食谱",
    noRecipesFound = "没有找到相关食谱",
    noRecipesFoundHint = "试试其他关键词",
    noRecipes = "还没有食谱",
    noRecipesHint = "点击 + 导入你的第一个食谱",
    generatingRecipe = "正在生成食谱...",
    tapToViewRecipe = "点击查看食谱",
    noCookbooks = "还没有食谱集",
    noCookbooksHint = "创建食谱集来整理你的食谱",
    createCookbook = "创建食谱集",
    newCookbook = "新建食谱集",
    cookbookName = "食谱集名称",
    deleteRecipe = "删除食谱？",
    cannotUndo = "此操作无法撤销。",
    ingredients = "食材",
    steps = "步骤",
    servings = "份量",
    addToCookbookBtn = "加入食谱集",
    addToMealPlan = "加入膳食计划",
    added = "已添加",
    startCooking = "开始烹饪",
    shareRecipe = "分享食谱",
    shareAsText = "以文字分享",
    shareAsTextHint = "复制食谱文字内容",
    shareAsImage = "以图片分享",
    shareAsImageHint = "生成食谱卡片图片",
    openSourceUrl = "打开来源链接",
    pullitRecipes = "Pullit Recipes",
    personalAssistant = "你的私人食谱助手",
    recipes = "食谱",
    favorites = "收藏",
    general = "通用",
    language = "语言",
    followSystem = "跟随系统",
    appearance = "外观",
    lightMode = "浅色模式",
    darkMode = "深色模式",
    autoDetectClipboard = "自动检测剪贴板",
    content = "内容",
    importExport = "导入 / 导出",
    support = "支持",
    privacyInfo = "隐私信息",
    privacyPolicy = "隐私政策",
    feedbackGroup = "反馈群组",
    rateUs = "给我们评分",
    aboutPullit = "关于 Pullit",
    account = "账户",
    email = "邮箱",
    displayName = "显示名称",
    signOut = "退出登录",
    signOutConfirm = "退出登录？",
    signOutMessage = "你可以随时重新登录。",
    version = "Pullit Recipes v1.0",
    importRecipe = "导入食谱",
    supportedPlatforms = "支持的平台",
    xiaohongshu = "小红书",
    douyin = "抖音",
    xiachufang = "下厨房",
    pasteLink = "粘贴链接或分享文字...",
    paste = "粘贴",
    orImportFrom = "或从以下导入",
    photo = "图片",
    text = "文字",
    link = "链接",
    image = "图片",
    pasteRecipeText = "粘贴食谱文字...",
    changeImage = "更换图片",
    chooseImage = "选择图片",
    selectedImage = "已选图片",
    weeklyPlan = "每周计划",
    groceryList = "购物清单",
    startPlanning = "开始计划",
    startPlanningHint = "添加食谱来规划你一周的膳食",
    addRecipes = "添加食谱",
    generateGroceryList = "生成购物清单",
    clearAll = "清除全部",
    inPlan = "已计划",
    serving = "份",
    servingsUnit = "份",
    aiRecommend = "AI 推荐",
    aiIngredientRecognition = "AI 食材识别",
    aiIngredientHint = "拍一张你的食材照片，我们会推荐你能做的食谱",
    choosePhoto = "选择照片",
    aiAnalyzing = "AI 分析中...",
    foundIngredients = "识别到的食材",
    addIngredient = "添加食材...",
    getAiSuggestions = "获取 AI 建议",
    newPhoto = "新照片",
    yourMatchingRecipes = "匹配的食谱",
    aiSuggestions = "AI 建议",
    generatingSuggestions = "生成建议中...",
    somethingWentWrong = "出了点问题",
    editRecipe = "编辑食谱",
    coverImage = "封面图片",
    addCoverPhoto = "添加封面",
    basicInfo = "基本信息",
    title = "标题",
    description = "描述",
    cookTime = "烹饪时间",
    nutrition = "营养成分",
    collapse = "收起",
    expand = "展开",
    calories = "热量",
    protein = "蛋白质",
    fat = "脂肪",
    carbs = "碳水",
    name = "名称",
    amount = "用量",
    section = "+ 分组",
    sectionOptional = "分组（可选）",
    addIngredient2 = "添加食材",
    addStep = "添加步骤",
    recipeRoulette = "食谱转盘",
    noRecipesToSpin = "没有可转的食谱",
    addSomeRecipes = "先添加一些食谱吧！",
    viewRecipe = "查看食谱",
    spinAgain = "再转一次",
    tapToSpin = "点击旋转",
    spinToPick = "转一转选食谱！",
    setTimer = "设置计时器",
    minutes = "分钟",
    seconds = "秒",
    start = "开始",
    pause = "暂停",
    play = "继续",
    reset = "重置",
    yourRecipeCompanion = "你的食谱伴侣",
    emailPlaceholder = "you@example.com",
    password = "密码",
    signUp = "注册",
    signIn = "登录",
    alreadyHaveAccount = "已有账户？登录",
    dontHaveAccount = "没有账户？注册",
    whatShouldWeCallYou = "我们怎么称呼你？",
    pickDisplayName = "为你的个人资料选一个显示名称。\n你可以之后再修改。",
    displayNamePlaceholder = "显示名称",
    atLeast2Chars = "至少2个字符",
    continueBtn = "继续",
    addAnItem = "添加项目...",
    noItemsYet = "还没有项目",
    noItemsHint = "添加项目或从膳食计划生成",
    toBuy = "待购",
    bought = "已购",
    clearBought = "清除已购",
    fromMealPlan = "来自膳食计划",
    recipeDetail = "食谱详情",
    savedToRecipes = "已保存到食谱",
    saveToRecipes = "保存到食谱",
    kcal = "千卡",
    step = "步骤",
    privacyTitle = "数据与隐私",
    privacySubtitle = "以下是 Pullit 在你使用 AI 功能时如何处理你的数据",
    privacyLocalStorageTitle = "本地存储",
    privacyLocalStorageDetail = "你的食谱、食谱集和膳食计划仅存储在你的设备上，不会上传至我们的服务器。",
    privacyDataSentTitle = "AI 功能数据传输",
    privacyDataSentDetail = "当你通过链接导入、拍照识别食材或使用 AI 推荐时，相关数据（链接或图片）会发送至我们的服务器进行处理。",
    privacyThirdPartyTitle = "第三方 AI 服务",
    privacyThirdPartyDetail = "我们的服务器使用 Groq (groq.com) 和 OpenRouter (openrouter.ai) 处理你的数据，用于食谱生成和食材识别。",
    privacyDataDeletionTitle = "即时删除",
    privacyDataDeletionDetail = "图片和视频数据在处理完成后立即删除，仅将结构化的食谱结果返回到你的设备。",
    privacyEncryptionTitle = "加密传输",
    privacyEncryptionDetail = "你的设备与我们服务器之间的所有数据传输均通过 HTTPS 加密。",
    privacyPolicyLink = "查看完整隐私政策",
    privacyAgreeButton = "同意并继续",
)

val LocalStrings = compositionLocalOf { EnglishStrings }
